# -*- coding: utf-8 -*-
"""Data Collection - MCU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qsap8EGNSYK_gDvy-c0PJ_BcWPF_OPx7
"""

#import relevant package
import twitter

#import key

CONSUMER_KEY = input()
CONSUMER_SECRET = input()
OAUTH_TOKEN = input()
OAUTH_TOKEN_SECRET = input()

#-- login to Twitter with all your authorization details
auth = twitter.oauth.OAuth(OAUTH_TOKEN, OAUTH_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_SECRET)

#-- Create a Twitter 'object' that we will be able to query in your code
twitter_api = twitter.Twitter(auth=auth)

#-- If this is successful and you've accessed twitter succesfully, nothining is displayed in python.
#-- but we will have at least a twitter 'object' we can use to access their services.
print(twitter_api)

#import stream
from twitter import *
from email.utils import parsedate

stream = TwitterStream(auth = auth, secure = True)
stream

#create loop stream
import pandas as pd
search_term = "MCU"
i=1
while i<1000:
    log = []
    try:
        tweet_stream = stream.statuses.filter(track = search_term)
        #-- create a loop that pauses until the next tweet arrives
        for tweet in tweet_stream:

            #-- put that tweet into our log 
            log.append(tweet)
            print(tweet["text"])
    #if the loop stop convert current log and save to csv from 1,2...
    except KeyError:
        df=pd.DataFrame(log)
        df.to_csv(str(i)+'.csv')
        i+=1
        continue

